### ISSUE TITLE
Question about conditioning

### ISSUE THREAD

**Issue by fay-askari72** [HighCWu/control-lora-v2#5]
Thank you for great work and repository. Could you please clarify what does "use_same_level_conditioning_latent" flag do? 

Thank you,

**Comment by HighCWu** [comment]
For example, ControlNet uses the 3-channel 512x512 image as the input to be downsampled 8 times to the same size as the 32x32 latent. When using the `use_conditioning_latent` option, we will encode 512x512 image with `vae` model to 32x32 latent and then upsample to 512x512 as the control input condition. `use_same_level_conditioning_latent` directly uses 32X32 latent as the control condition. There is no additional downsample steps.

**Comment by fay-askari72** [comment]
Got it, thank you for prompt response.
